# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{attachment_on_the_fly}
  s.version = "0.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Sutherland"]
  s.date = %q{2010-11-08}
  s.description = %q{A Paperclip mix-in to allow auto-generation of resized images}
  s.email = %q{jefferey.sutherland@gmail.com}
  s.extra_rdoc_files = [
    "README",
     "README.rdoc"
  ]
  s.files = [
    "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "attachment_on_the_fly.gemspec",
     "init.rb",
     "lib/attachment_on_the_fly.rb"
  ]
  s.homepage = %q{http://github.com/drpentode/Attachment-on-the-Fly}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A Paperclip mix-in to allow auto-generation of resized images}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
    else
      s.add_dependency(%q<paperclip>, [">= 0"])
    end
  else
    s.add_dependency(%q<paperclip>, [">= 0"])
  end
end

