# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{attachment_on_the_fly}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Sutherland"]
  s.date = %q{2009-11-19}
  s.description = %q{A Paperclip mix-in to allow auto-generation of resized images}
  s.email = %q{jefferey.sutherland@gmail.com}
  s.extra_rdoc_files = [
    "README",
     "README.rdoc"
  ]
  s.files = [
    "README",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "attachment_on_the_fly.gemspec",
     "init.rb",
     "lib/attachment_on_the_fly.rb",
     "pkg/attachment_on_the_fly-0.0.0.gem",
     "pkg/attachment_on_the_fly-0.0.1.gem",
     "pkg/attachment_on_the_fly-0.0.2.gem",
     "pkg/attachment_on_the_fly-0.0.3.gem"
  ]
  s.homepage = %q{http://github.com/drpentode/Attachment-on-the-Fly}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A Paperclip mix-in to allow auto-generation of resized images}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
