# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: attachment_on_the_fly 0.1.3 ruby lib

Gem::Specification.new do |s|
  s.name = "attachment_on_the_fly"
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Sutherland", "Ben Ellis", "Blake Hyde", "twonegatives"]
  s.date = "2013-12-05"
  s.description = "A Paperclip mix-in to allow auto-generation of resized images"
  s.email = "jefferey.sutherland@gmail.com"
  s.extra_rdoc_files = [
    "README",
    "README.rdoc"
  ]
  s.files = [
    "README",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "attachment_on_the_fly.gemspec",
    "init.rb",
    "lib/attachment_on_the_fly.rb",
    "spec/attachment_on_the_fly_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/drpentode/Attachment-on-the-Fly"
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "A Paperclip mix-in to allow auto-generation of resized images"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
    else
      s.add_dependency(%q<paperclip>, [">= 0"])
    end
  else
    s.add_dependency(%q<paperclip>, [">= 0"])
  end
end

