# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{on_the_fly}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Jeff Sutherland}, %q{Travis Pessetto}]
  s.date = %q{2011-08-10}
  s.description = %q{A Paperclip mix-in to allow auto-generation of resized images.  Modded to delete images
	and rename the thumb works on only the ES3 AMS system right now.}
  s.email = %q{travis@pessetto.com}
  s.extra_rdoc_files = [
    "README",
    "README.rdoc"
  ]
  s.files = [
    "README",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "init.rb",
	"lib/on_the_fly.rb"
  ]
  s.homepage = %q{http://pessetto.com}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{A Paperclip mix-in to allow auto-generation of resized images}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
    else
      s.add_dependency(%q<paperclip>, [">= 0"])
    end
  else
    s.add_dependency(%q<paperclip>, [">= 0"])
  end
end

